# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: false
branches:
  only:
  - master
  - /release-.*/
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  # - julia -e 'Pkg.clone(pwd()); Pkg.build("Query"); Pkg.test("Query"; coverage=true)'
after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'include("make.jl")'
  